import Head from 'next/head';
import Footer from '../../footer/Footer';
import Header from '../../header/navigetion/Header';

export interface IPrimaryLayout extends React.ComponentPropsWithoutRef<'div'> {
  justify?: 'items-center' | 'items-start';
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({
  children,
  justify = 'items-center',
  ...divProps
}) => {
  return (
    <>
       <Head>
        <title>Superfandom - NFT's Donation Animated landing page</title>
        <meta name="description" content="Generated by create next Webapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div {...divProps} className="w-full bg-primary ">
        <Header />
        <main className="w-full main-wrapper--box">{children}</main>
        <div className="m-auto" />
        <Footer />
      </div>
    </>
  );
};

export default PrimaryLayout;