import Head from 'next/head';
import Footer from '../../footer/Footer';
import Navigation from '../../header/navigation/Navigation';

export interface IPrimaryLayout extends React.ComponentPropsWithoutRef<'div'> {
  justify?: 'items-center' | 'items-start';
  headerNext:boolean;
}

const PrimaryLayout: React.FC<IPrimaryLayout> = ({
  children,
  justify = 'items-center',
  headerNext,
  ...divProps
}) => {
  return (
    <>
       <Head>
        <title>{`Superfandom - NFT's Donation Animated landing page`}</title>
        <meta name="description" content="Generated by create next Webapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div {...divProps} className={`w-full bg-primary`}>
        <Navigation headerNext={headerNext}/>
        <main className="w-full main-wrapper--box">{children}</main>
        <div className="m-auto" />
        <Footer />
      </div>
    </>
  );
};

export default PrimaryLayout;