import Head from 'next/head';
import { IPrimaryLayout } from '../../../../typings/types';
import Footer from '../../footer/Footer';
import Navigation from '../../header/navigation/Navigation';


const PrimaryLayout: React.FC<IPrimaryLayout> = ({
  children,
  justify = 'items-center',
  headerNext,
  pageName,
  ...divProps
}) => {
  return (
    <>
       <Head>
        <title>{`Superfandom - NFT's Donation Animated landing page`}</title>
        <meta name="description" content="Generated by create next Webapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div {...divProps} className={`w-full bg-primary`}>
        <Navigation headerNext={headerNext} pageName={pageName}/>
        <main className="w-full main-wrapper--box">{children}</main>
        <div className="m-auto" />
        <Footer pageName={pageName}/>
      </div>
    </>
  );
};

export default PrimaryLayout;