import Head from 'next/head';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';
import Exclusive from '../components/Exclusive/Exclusive';
import TokenCollection from '../components/c-s-token/TokensCollection';
import Banner4 from '../components/banner/Banner4';
const CampaignListing: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>Campaign Listing Page - NFT's Superfundom Animation Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner4 title={''} subtitle={''} desc={''} />
      <Exclusive />
      <TokenCollection />
    </div>
  );
};

export default CampaignListing;

CampaignListing.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
