import Head from 'next/head';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';
import Exclusive from '../components/Exclusive/Exclusive';
import TokenCollection from '../components/c-s-token/TokensCollection';
import CampaignBanner from '../components/banner/CampaignBanner';

const CampaignListing: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>{`Campaign Listing Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CampaignBanner  />
      <Exclusive />
      <TokenCollection />
    </div>
  );
};

export default CampaignListing;

CampaignListing.getLayout = (page) => {
  return <PrimaryLayout headerNext={true}>{page}</PrimaryLayout>;
};
