import Head from 'next/head';
import CampaignBanner from '../components/core/banner/CampaignBanner';
import CSToken from '../components/shared/c-s-token/CSToken';
import Exclusive from '../components/shared/Exclusive/Exclusive';
import PrimaryLayout from '../components/shared/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';


const Campaign: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>{`Campaign Listing Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CampaignBanner />
      <Exclusive pageName={"campaign"} />
      <CSToken pageName={"campaign"} title={"collections"} />
    </div>
  );
};

export default Campaign;

Campaign.getLayout = (page) => {
  return <PrimaryLayout pageName={"campaign"} headerNext={true}>{page}</PrimaryLayout>;
};
