import Head from 'next/head';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';
import Banner2 from '../components/banner/Banner2';
import FaqPage from '../components/FAQ/Faq';
import ActiveDrop from '../components/ActiveDrop/ActiveDrop';
import CSToken from '../components/c-s-token/CSToken';
import HowItWork2 from '../components/how-it-work/HowItWork2';

const CausesPage: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>Causes Page - NFT's Superfundom Animation Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner2 title={''} subtitle={''} desc={''} />
       <ActiveDrop />
       <CSToken />
       <HowItWork2 />
      <FaqPage />
      
    </div>
  );
};

export default CausesPage;

CausesPage.getLayout = (page) => {
  return <PrimaryLayout headerNext={false}>{page}</PrimaryLayout>;
};
