import Head from 'next/head';
import { NextPageWithLayout } from './page';
import FaqPage from '../components/shared/Faq/Faq';
import CausesBanner from '../components/core/banner/CausesBanner';
import ActiveDrop from '../components/shared/ActiveDrop/ActiveDrop';
import CSToken from '../components/shared/c-s-token/CSToken';
import HowItWork2 from '../components/core/how-it-work/HowItWork2';
import PrimaryLayout from '../components/shared/layouts/primary/PrimaryLayout';


const CausesPage: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>{`Causes Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CausesBanner />
      <ActiveDrop />
      <CSToken pageName={"causes"} title={"collect soulbound tokens"} />
      <HowItWork2 pageName={"causes"} />
      <FaqPage />
    </div>
  );
};

export default CausesPage;

CausesPage.getLayout = (page) => {
  return <PrimaryLayout pageName={"causes"} headerNext={false}>{page}</PrimaryLayout>;
};
