import Head from 'next/head';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';
import CausesBanner from '../components/banner/CausesBanner';
import FaqPage from '../components/Faq/Faq';
import ActiveDrop from '../components/ActiveDrop/ActiveDrop';
import CSToken from '../components/c-s-token/CSToken';
import HowItWork2 from '../components/how-it-work/HowItWork2';

const CausesPage: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>{`Causes Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CausesBanner />
       <ActiveDrop />
       <CSToken pageName={"causes"}/>
      <HowItWork2 pageName={"causes"} />
      <FaqPage />
    </div>
  );
};

export default CausesPage;

CausesPage.getLayout = (page) => {
  return <PrimaryLayout pageName={"causes"} headerNext={false}>{page}</PrimaryLayout>;
};
