import Head from 'next/head';
import { GetStaticProps } from 'next';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';
import CausesBanner from '../components/banner/CausesBanner';
import FaqPage from '../components/FAQ/Faq';
import ActiveDrop from '../components/ActiveDrop/ActiveDrop';
import CSToken from '../components/c-s-token/CSToken';
import HowItWork2 from '../components/how-it-work/HowItWork2';
import { ApiClient } from '../utils/api-client';

export interface ICausesPage {
  drops: any;
}

const CausesPage: NextPageWithLayout<ICausesPage> = ({ drops }) => {
  return (
    <div className="container-wrapper">
      <Head>
        <title>{`Causes Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CausesBanner />
      <ActiveDrop drops={drops} />
      <CSToken pageName={'causes'} />
      <HowItWork2 pageName={'causes'} />
      <FaqPage />
    </div>
  );
};

export default CausesPage;

CausesPage.getLayout = (page) => {
  return <PrimaryLayout headerNext={false}>{page}</PrimaryLayout>;
};

export const getStaticProps: GetStaticProps = async () => {
  const result = await ApiClient.get('/drops?withCollections=true');

  const drops = result.data;

  return {
    props: {
      drops,
    },

    revalidate: 60 * 60, // 1 hour
  };
};
