import Head from 'next/head';
import Banner from '../components/banner/Banner';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';

const DetailsPage2: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
      <title>NFT'S Details Page Two - NFT's Superfundom Animate Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </div>
  );
};

export default DetailsPage2;

DetailsPage2.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
