import Head from 'next/head';
import ProductDetails from '../components/core/ProductDetails/ProductDetails';
import Exclusive from '../components/shared/Exclusive/Exclusive';
import PrimaryLayout from '../components/shared/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';


const DetailsPage: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper bg-secondary">
      <Head>
        <title>{`Details Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetails />
      <Exclusive />
      <div className="spacher h-[50px]"></div>
    </div>
  );
};

export default DetailsPage;

DetailsPage.getLayout = (page) => {
  return <PrimaryLayout headerNext={true}>{page}</PrimaryLayout>;
};
