import Head from 'next/head';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';
import FaqPage from '../components/FAQ/Faqt';
import ActiveDrop from '../components/ActiveDrop/ActiveDrop';
import NFTToken from '../components/c-s-token/NFTToken';
import HowItWork3 from '../components/how-it-work/HowItWork3';
import Banner3 from '../components/banner/Banner3';

const Fundom: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>Fundom Page - NFT's Superfundom Animation Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Banner3 title={''} subtitle={''} desc={''} /> */}
      <Banner3 title={''} subtitle={''} desc={''} />
      <ActiveDrop />
      <NFTToken />
      <HowItWork3 />
      <FaqPage />
    </div>
  );
};

export default Fundom;

Fundom.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
