import Head from 'next/head';
import Banner from '../components/banner/Banner';
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from './page';

const FundomPage: NextPageWithLayout = () => {

  return (
    <>
    <div className="container-wrapper">
      <Head>
        <title>Superfandom Fandoms - NFT's Animate Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </div>
    </>
  );
};

export default FundomPage;

FundomPage.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
