import Head from 'next/head';
import { NextPageWithLayout } from './page';
import FaqPage from '../components/shared/Faq/Faq';
import Banner from '../components/core/banner/Banner';
import TextImgSiniped from '../components/core/text-and-img-siniped/TextImgSiniped';
import HowItWork from '../components/core/how-it-work/HowItWork';
import Explore from '../components/core/explore-and-collect/Explore';
import PrimaryLayout from '../components/shared/layouts/primary/PrimaryLayout';


const Home: NextPageWithLayout = () => {

  return (
    <div className="container-wrapper">
      <Head>
        <title>{`Home Page - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <TextImgSiniped />
      <HowItWork card1={true} card2={false} pageName={"home"} />
      <Explore />
      <FaqPage />
    </div>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <PrimaryLayout headerNext={false}>{page}</PrimaryLayout>;
};
