import Head from 'next/head';
import PrimaryLayout from '../../components/layouts/primary/PrimaryLayout';
import { NextPageWithLayout } from '../page';
import Exclusive from '../../components/Exclusive/Exclusive';
import ProductDetails2 from '../../components/ProductDetails/ProductDetails2';

const Id: NextPageWithLayout = () => {
  return (
    <div className="container-wrapper bg-secondary">
      <Head>
        <title>{`Details Page-2 - NFT's Superfandom Animation Landing Page`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetails2 />
      <Exclusive />
      <div className="spacher h-[50px]"></div>
    </div>
  );
};

export default Id;

Id.getLayout = (page) => {
  return <PrimaryLayout headerNext={true}>{page}</PrimaryLayout>;
};
